name: Event demo 
on:
  pull_request:
    types:
      - opened
    branches:
      - master
      - 'dev-*' 
      - "feat/**"
  workflow_dispatch:

  push:
    branches:
      - master
      - "dev-*"
      - "feat/**"
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{toJSON(github.event)}}"
      - name: get code
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: build code
        run: npm run build
      - name: deploy project
        run: echo "deploying..."